auth:
  service: auth-git-hook
  triggerBucket: auth-ci-ir-webhook-bucket
  deploymentBucket: auth-ci-ir-serverless-deployment

collabo:
  service: Auth-Git-Hook
  triggerBucket: auth-ci-webhook-bucket
  deploymentBucket: auth-ci-serverless-deployment