auth:
  service: AuthGitHookWithBatch
  triggerBucket: auth-ci-ir-webhook-bucket
  deploymentBucket: auth-ci-ir-serverless-deployment

collabo:
  service: AuthGitHookWithBatch
  triggerBucket: auth-ci-webhook-bucket
  deploymentBucket: auth-ci-serverless-deployment
