service: GitHookWithBatch
tableName: GitHookWithBatchRepo
auth:
  triggerBucket: auth-ci-ir-webhook-bucket
  deploymentBucket: auth-ci-ir-serverless-deployment

collabo:
  triggerBucket: auth-ci-webhook-bucket
  deploymentBucket: auth-ci-serverless-deployment
