Resources:
  WebHookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      AttributeDefinitions:
        - AttributeName: Repository
          AttributeType: S
        - AttributeName: Events
          AttributeType: S
          # sperate each event name with ",", allowed names are "push" "pull_request" "commit"
      KeySchema:
        - AttributeName: Repository
          KeyType: HASH
        - AttributeName: Events
          KeyType: RANGE