Resources:
  WebHookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
#      BillingMode: PROVISIONED
#      ProvisionedThroughput:
#        ReadCapacityUnits: 2
#        WriteCapacityUnits: 2
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Repository
          AttributeType: S
        - AttributeName: Events
          AttributeType: S
      KeySchema:
        - AttributeName: Repository
          KeyType: HASH
        - AttributeName: Events
          KeyType: RANGE